services:
  db:
    image: postgres:15-alpine
    container_name: uniwork_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: uniwork_db
      POSTGRES_USER: uniwork_user
      POSTGRES_PASSWORD: uniwork_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: